### ISSUE TITLE
MCP251XFD_INT_SPI_CRC_EVENT

### ISSUE THREAD

**Issue by mickeyl** [Emandhal/MCP251XFD#12]
When using the `MCP251XFD_DRIVER_USE_READ_WRITE_CRC` driver configuration, I'm always getting `MCP251XFD_INT_SPI_CRC_EVENT` set in the interrupt flags. When reading the CRC register, it tells me `MCP251XFD_CRC_FORMERR_EVENT` is set, i.e. a format error.

This is quite odd, because a) I have verified that `nCS` is properly handled (not release before the last byte has been transmitted) and b) everything else still seems to work fine. Even letting `nCS` low for some cycles longer does not change the problem.

Do you have any idea what else could be the problem?

(And perhaps a side question... do you think CRC communication is necessary at all?)

**Comment by Emandhal** [comment]
SPI CRC format error is, as you notice, a frame with a CRC with a byte missing.
To verify, the best is a Logic analyser. 
If you really have a byte missing, you should not be able to read the CRC registrer...

I have used the CRC on a critical system where all all data needs an integrity check.
If you think, in your application, it is not necessary to use it, you can stay in normal mode

**Comment by mickeyl** [comment]
This looks all good, doesn't it?

![Bildschirmfoto vom 2023-12-08 13-09-35](https://github.com/Emandhal/MCP251XFD/assets/167469/d8b4eda7-e639-4df4-bf4e-277ade73d4fe)

**Comment by Emandhal** [comment]
Yes, it looks perfect.
Do you use the MCP2517FD or the MCP2518FD?
If you use the MCP2517FD, this device is quite tough regarding the SPI (see §17 of the driver library guide or the MCP2517FD errata DS80000792B).

**Comment by mickeyl** [comment]
Yeah, I know, no, it's the MCP2518FD. It's really strange. I will crosscheck with another MCP. But since it's definitely not a driver issue, I'll close this here. Thanks.
