### ISSUE TITLE
CAN Listen Only Mode.

### ISSUE THREAD

**Issue by mikucukyilmaz** [Emandhal/MCP251XFD#3]
We couldn't find any method to start the controller in Listen Only Mode. We added the method below and going to test it. We would like to ask if we missed that function.

```
inline eERRORRESULT MCP251XFD_StartCANListenOnly(MCP251XFD *pComp)
{
  return MCP251XFD_RequestOperationMode(pComp, MCP251XFD_LISTEN_ONLY_MODE, false);
}
```

**Comment by Emandhal** [comment]
Hi,
This should work as expected.

**Comment by mikucukyilmaz** [comment]
Yep tested and it's working okay. Thanks.
