### ISSUE TITLE
Struct "MCP251XFD" has no field "GPIOsOutLevel"

### ISSUE THREAD

**Issue by mickeyl** [Emandhal/MCP251XFD#9]
Any idea what could cause this problem? Is "HEAD" supposed to compile or work in progress? Should I base my integration on a certain revision in git?

**Comment by Emandhal** [comment]
I'm so sorry, for the moment I'm working on this driver.
I shouldn't have commit non compiling work

A good revision is the commit 290fdc5acd4b9f7cf26982dbfc9c08d1d2cf6e4e on April, 1st

**Comment by mickeyl** [comment]
Thanks, I will go from there.
